/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Despesas: () => import('#controllers/despesas_controller'),
  Parlamentares: () => import('#controllers/parlamentares_controller'),
  Ranking: () => import('#controllers/ranking_controller'),
}
